services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: prueba
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
        - net
    restart: unless-stopped
  app:
    build: .
    container_name: tty_for_python
    stdin_open: true
    tty: true
    volumes:
      - '.:/code'
    depends_on:
      - postgres
    networks:
      - net

volumes:
  postgres_data:
  app_data:

networks:
  net:
